language: none
sudo: required
install:
  - wget https://launchpad.net/ubuntu/+source/shellcheck/0.4.4-4/+build/11197881/+files/shellcheck_0.4.4-4_amd64.deb
  - sudo dpkg -i shellcheck_0.4.4-4_amd64.deb

script:
  - shellcheck *.sh

notifications:
  email: false
